sudo: required
services:
   - docker
before_install:
   - docker build -t allwin.j/docker-reactapp -f Dockerfile.dev .
script:
   - docker run allwin.j/docker-reactapp npm run test -- --coverage
deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-ap-south-1-878963179285"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
     secure: "$AWS_SECRET_KEY"
